version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      next:
        patterns:
          - "next"
          - "eslint-config-next"
      typescript:
        patterns:
          - "@types/node"
          - "typescript"
      dev-tools:
        patterns:
          - "eslint"
          - "prettier*"
    open-pull-requests-limit: 5
    reviewers:
      - "amotarao"
    commit-message:
      prefix: "deps"
      include: "scope"
