version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "next*"
      typescript-ecosystem:
        patterns:
          - "@types/*"
          - "typescript"
      dev-tools:
        patterns:
          - "eslint*"
          - "prettier*"
    open-pull-requests-limit: 5
    reviewers:
      - "amotarao"
    commit-message:
      prefix: "deps"
      include: "scope"
